version: "3.7"
services:
  web:
    container_name: benny_wasender_container
    build:
      context: .
      dockerfile: Dockerfile
      image: benny_wasender
    ports:
      - "9001:9001"
    restart: unless-stopped