version: "3.7"
services:
  web:
    container_name: kanglerian_wablast_container
    image: kanglerian/kanglerian_wasender:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=7002 # Sesuaikan port dengan kebutuhan Anda
    ports:
      - "${PORT}:7002" # Expose port yang sesuai
    restart: unless-stopped
