version: "3.7"
services:
  web:
    container_name: kanglerian_wasender_container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=7001
    ports:
      - "${PORT}:7001"
    restart: unless-stopped